### ISSUE TITLE
Legion errors

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/MountMe#7] opened 2016-07-24 23:28 UTC
I liked that this addon supported movement spells like Roll and Sprint, so wanted to give it a try. It does not seem to work at all in Legion however. First there is an ignorable script error warning, then some other error after. Anyway, here are the errors...

["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'AddonLoader' tried to call the protected function 'SetAllowDangerousScripts()'.",
["stack"] = "Interface\\AddOns\\!BugGrabber\\BugGrabber.lua:573: in function <Interface\\AddOns\\!BugGrabber\\BugGrabber.lua:573>\n[C]: in function `SetAllowDangerousScripts'\nInterface\\FrameXML\\StaticPopup.lua:3641: in function `OnAccept'\nInterface\\FrameXML\\StaticPopup.lua:4256: in function `StaticPopup_OnClick'\n[string \"*:OnClick\"]:1: in function <[string \"*:OnClick\"]:1>",

["message"] = "[string \"C_MountJournal.Summon(0)\"]:1: attempt to call field 'Summon' (a nil value)",
["locals"] = "(*temporary) = nil\n(*temporary) = 0\n(*temporary) = \"attempt to call field 'Summon' (a nil value)\"\n",
["stack"] = "[string \"C_MountJournal.Summon(0)\"]:1: in main chunk\n[C]: in function `RunScript'\nInterface\\FrameXML\\ChatFrame.lua:2051: in function `?'\nInterface\\FrameXML\\ChatFrame.lua:4332: in function <Interface\\FrameXML\\ChatFrame.lua:4279>\n[C]: in function `ChatEdit_ParseText'\nInterface\\FrameXML\\ChatFrame.lua:4000: in function <Interface\\FrameXML\\ChatFrame.lua:3999>\n[C]: in function `ChatEdit_SendText'\nInterface\\FrameXML\\ChatFrame.lua:2631: in function <Interface\\FrameXML\\ChatFrame.lua:2624>\n[C]: in function `RunMacroText'\nInterface\\FrameXML\\SecureTemplates.lua:435: in function `handler'\nInterface\\FrameXML\\SecureTemplates.lua:621: in function <Interface\\FrameXML\\SecureTemplates.lua:569>",

**Comment by Phanx** [comment] 2016-07-28 11:52
The first error appears to be caused by AddonLoader, or at least isn't caused by MountMe, which doesn't call the indicated function anywhere.

The second error should be fixed in 7.0.3.0.

**Closed by Phanx** 2016-07-28 11:52 UTC
